import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";

const SourceCodePro = Source_Code_Pro({
  variable: "--font-source-code",
  subsets: ["latin"],
});

const MonumentExtended = localFont({
  src: [
    {
      path: "../fonts/PPMonumentExtended-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PPMonumentExtended-Black.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/PPMonumentExtended-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/PPMonumentExtended-BlackItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../fonts/PPMonumentExtended-Ultrabold.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-monument-extended",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${SourceCodePro.variable} ${MonumentExtended.variable} antialiased noise`}
      >
        <ThemeProvider
          attribute="class"
            defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
